CREATE TABLE student (
                         student_id  BIGINT PRIMARY KEY,
                         age         INTEGER NOT NULL,
                         name        VARCHAR(50) NOT NULL,
                         faculty_id  BIGINT REFERENCES faculty(faculty_id)
);

ALTER TABLE student ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY;